-- 1.WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
	SELECT * FROM EMP WHERE SAL >
	(SELECT SAL FROM EMP WHERE ENAME='ADAMS');--11rows

-- 2.WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING --13rows
	 SELECT ENAME,SAL FROM EMP WHERE SAL<
 	 (SELECT SAL FROM EMP WHERE ENAME='KING');

-- 3.WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
	SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=
	(SELECT DEPTNO FROM EMP WHERE ENAME='JONES');