-- 1.WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
	SELECT ENAME FROM EMP WHERE SAL >
		(SELECT SAL FROM EMP WHERE ENAME='ADAMS');--11rows

-- 2.WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING --13rows
	 SELECT ENAME,SAL FROM EMP WHERE SAL<
 	 	(SELECT SAL FROM EMP WHERE ENAME='KING');

-- 3.WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
	SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=
		(SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

-- 4.WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
 	SELECT ENAME,JOB FROM EMP WHERE JOB=
 		(SELECT JOB FROM EMP WHERE ENAME='JAMES');


-- 5.WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE  EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
	SELECT EMPNO,ENAME,SAL*12 AS ANNUAL_SALARY FROM EMP WHERE SAL*12>
		(SELECT SAL*12 FROM EMP WHERE ENAME='WARD')


-- 6.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT 
	SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE<
		(SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT')


-- 7.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT 
	SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE>
		(SELECT HIREDATE FROM EMP WHERE JOB='PRESIDENT')


-- 8.WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
	SELECT ENAME,SAL FROM EMP WHERE SAL<
		(SELECT SAL FROM EMP WHERE EMPNO=7839);


-- 9.WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN 
	SELECT ENAME,EMPNO FROM EMP WHERE SAL>
		(SELECT SAL FROM EMP WHERE ENAME='ALLEN');


-- 10.WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN 
	SELECT ENAME, SAL FROM EMP WHERE SAL>
		(SELECT SAL FROM EMP WHERE ENAME='MILLER')
		AND SAL<
		(SELECT SAL FROM EMP WHERE ENAME='ALLEN');


-- 11.WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 

	SELECT * FROM EMP WHERE DEPTNO=20
		AND
		JOB =(SELECT JOB FROM EMP WHERE ENAME='SMITH');


-- 12.WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER 
	SELECT * FROM EMP WHERE JOB='MANAGER'
		AND
		DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');


-- 13.WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 
	SELECT ENAME,HIREDATE FROM EMP WHERE 
		HIREDATE>'31-DEC-1980' 
		AND	
		HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='KING');


-- 14.WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500	
	SELECT ENAME,SAL, SAL*12 AS ANNUAL_SALARY FROM EMP WHERE SAL*12>3500
		AND
		SAL*12<(SELECT SAL*12 FROM EMP WHERE ENAME='BLAKE');


-- 15.WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING 
	SELECT * FROM EMP WHERE SAL>
		(SELECT SAL FROM EMP WHERE ENAME='SCOTT')
		AND
		SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');


-- 16.WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 
	SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%'
		AND 
		DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');


-- 17.WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH 
	SELECT ENAME,COMM FROM EMP WHERE COMM IS NOT NULL
		AND
		JOB=(SELECT JOB FROM EMP WHERE ENAME='SMITH')


-- 18.WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER 
	SELECT * FROM EMP WHERE JOB='CLERK'
		AND
		DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='TURNER')


-- 19.WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING	
	SELECT ENAME,SAL,JOB,SAL*12 AS ANNUAL_SALARY
		FROM EMP WHERE
		SAL*12>(SELECT SAL*12 FROM EMP WHERE ENAME='SMITH')
		AND
		SAL*12<(SELECT SAL*12 FROM EMP WHERE ENAME='KING');

-- 20.WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM SALARY 
	SELECT ENAME FROM EMP WHERE SAL IN
		(SELECT MIN(SAL) FROM EMP );


-- 21.WAQTD NAME AND HIREDATE OF THE EMPLOYEE HIRED BEFORE ALL THE EMPLOYEES (FIRST EMP)
	SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE IN
		(SELECT MIN(HIREDATE) FROM EMP);


-- 22.WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AT THE LAST 
	SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE IN	
		(SELECT MAX(HIREDATE)FROM EMP);


-- 23.WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMISSION 
	SELECT ENAME,COMM FROM EMP WHERE COMM IN
		(SELECT MIN(COMM)FROM EMP);


-- 24.WAQTD NAME, SAL AND COMM OF THE EMPLOYEE EARNING MAXIMUM COMISSION 
	SELECT ENAME,SAL,COMM FROM EMP WHERE COMM IN
		(SELECT MAX(COMM) FROM EMP);


-- 25.WAQTD DETAILS OF THE EMPLOYEE WHO HAS GREATEST EMPNO 
	SELECT * FROM EMP WHERE EMPNO IN
		(SELECT MAX(EMPNO) FROM EMP );


-- 26.WAQTD DETAILS OF THE EMPLOYEES HAVING THE LEAST HIREDATE 
	SELECT * FROM EMP WHERE HIREDATE IN
		(SELECT MIN(HIREDATE)FROM EMP) ;


-- 27.WAQTD DETAILS OF THE EMPLOYEES EARNING LEAST ANNUAL SALARY 
	SELECT * FROM EMP WHERE SAL*12 IN
		(SELECT MIN(SAL*12) FROM EMP);


-- 28.WAQTD NAME , ANNUAL SALARY OF THE EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN
	SELECT ENAME,SAL*12  FROM EMP WHERE SAL*12 >ALL
		(SELECT SAL*12 FROM EMP WHERE JOB='SALESMAN');


-- 29.WAQTD 2ND MINIMUM SALARY 
	SELECT * FROM EMP WHERE SAL=
		(SELECT MIN(SAL) FROM EMP WHERE SAL>
		(SELECT MIN(SAL) FROM EMP));


-- 30.WAQTD 5TH MAXIMUM SALARY 
	SELECT * FROM EMP WHERE SAL =
	    (SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP)))));
	

-- 31.WAQTD NAME OF THE EMPLOYEE SAL WHO IS EARNING 3RD MAXIMUM SALARY 
	SELECT ENAME FROM EMP WHERE SAL =
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP)));



-- 32.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY 
	SELECT EMPNO FROM EMP WHERE SAL =
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP));


-- 33.WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
	SELECT DNAME FROM DEPT WHERE DEPTNO IN
		(SELECT DEPTNO FROM EMP WHERE SAL =
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP WHERE SAL <
		(SELECT MAX(SAL) FROM EMP)))));


-- 34.WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd
	SELECT * FROM EMP WHERE HIREDATE =
	    (SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE >
		(SELECT MIN(HIREDATE) FROM EMP));


-- 35.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
	SELECT ENAME FROM EMP WHERE HIREDATE =
	    (SELECT MAX(HIREDATE) FROM EMP WHERE HIREDATE <
		(SELECT MAX(HIREDATE) FROM EMP));


-- 36.WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
	SELECT LOC FROM DEPT WHERE DEPTNO =
		(SELECT DEPTNO FROM EMP WHERE HIREDATE =
		(SELECT MIN(HIREDATE) FROM EMP));


-- 37.WAQTD SMITHS REPORTING MANAGER'S NAME 
	 SELECT ENAME FROM EMP WHERE EMPNO IN
	 	(SELECT MGR FROM EMP WHERE ENAME='SMITH');


-- 38.WAQTD ADAMS MANAGER'S MANAGER NAME 
	 SELECT ENAME FROM EMP WHERE EMPNO IN
	 	(SELECT MGR FROM EMP WHERE EMPNO IN
	 	(SELECT MGR FROM EMP WHERE ENAME='ADAMS'));


-- 39.WAQTD DNAME OF JONES MANAGER
	SELECT DNAME FROM DEPT WHERE DEPTNO=
		(SELECT DEPTNO FROM EMP WHERE EMPNO IN
		(SELECT MGR FROM EMP WHERE ENAME='JONES'));


-- 40.WAQTD MILLER'S MANAGER'S SALARY 
	SELECT SAL FROM EMP WHERE EMPNO=
		(SELECT MGR FROM EMP WHERE ENAME='MILLER');


-- 41.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
	SELECT LOC FROM DEPT WHERE DEPTNO =
		(SELECT DEPTNO FROM EMP WHERE EMPNO IN
		(SELECT MGR FROM EMP WHERE EMPNO IN
		(SELECT MGR FROM EMP WHERE ENAME='SMITH')));


-- 42.WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE 
	SELECT ENAME FROM EMP WHERE MGR=
	 (SELECT EMPNO FROM EMP WHERE ENAME='BLAKE');


-- 43.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING 
	SELECT COUNT(ENAME) FROM EMP WHERE MGR =
		(SELECT EMPNO FROM EMP WHERE ENAME='KING');


-- 44.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES 
	SELECT * FROM EMP WHERE MGR =
		(SELECT EMPNO FROM EMP WHERE ENAME='JONES');


-- 45.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER 
	SELECT ENAME FROM EMP WHERE MGR IN
		(SELECT EMPNO FROM EMP WHERE EMPNO IN
		(SELECT MGR FROM EMP WHERE ENAME='BLAKE'));


-- 46.WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
	SELECT COUNT(ENAME) FROM EMP WHERE MGR IN
		(SELECT EMPNO FROM EMP WHERE EMPNO IN
		(SELECT MGR FROM EMP WHERE ENAME='FORD'));